// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHlBaDf-g0863zoXqz0Ikyn2jo9RWAcmA',
    appId: '1:253126900408:web:31e0c4cd14f594415ed24d',
    messagingSenderId: '253126900408',
    projectId: 'parcialdiferido',
    authDomain: 'parcialdiferido.firebaseapp.com',
    storageBucket: 'parcialdiferido.appspot.com',
    measurementId: 'G-S6JD6LMB2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu10OVQ_JYA66nKth_Ir755AVYWfxVqn4',
    appId: '1:253126900408:android:d452e71206576d1f5ed24d',
    messagingSenderId: '253126900408',
    projectId: 'parcialdiferido',
    storageBucket: 'parcialdiferido.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCDnEArDMdu9GEsSN2MbPOfMKsQWnMYNw',
    appId: '1:253126900408:ios:6b50f95d339d880d5ed24d',
    messagingSenderId: '253126900408',
    projectId: 'parcialdiferido',
    storageBucket: 'parcialdiferido.appspot.com',
    iosBundleId: 'com.example.flutterParcial4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCDnEArDMdu9GEsSN2MbPOfMKsQWnMYNw',
    appId: '1:253126900408:ios:6b50f95d339d880d5ed24d',
    messagingSenderId: '253126900408',
    projectId: 'parcialdiferido',
    storageBucket: 'parcialdiferido.appspot.com',
    iosBundleId: 'com.example.flutterParcial4',
  );
}
